### ISSUE TITLE
タグ付け方法の調査

### ISSUE THREAD

**Issue by Adachi-Yuta458** [Adachi-Yuta458/QcareA#39]

**Comment by Adachi-Yuta458** [comment]
## ゴール
介護側が質問する際に、「請求に関すること」「人員基準に関すること」のようなタグをつけることで利便性向上を目指す
タグ付け実装のissueに入る前に、このissueで方向性を調べ、レビューを受けてから実装に移る

## 手順
1. 今回、必要となるタグを全て保存しておくTagテーブルを用意する
2. QuestionテーブルとTagテーブルの中間テーブルとして、選択されたタグを保存しておくQuestionTagテーブルを用意する
3. 関連付けを行う。questionモデルはquestion_tagをhas_manyで、tagをquestion_tagを通してhas_manyで持っている
4. tagモデルから見ても質問は複数持っているので、question_tagをhas_manyで、questionをquestion_tagを通してhas_manyで持っている
5. ビュー側のformの中でcollection_check_boxesメソッドを使って、question_tagにtag_idを保存する

**Comment by TomoyaIkarashi0023** [comment]
@Adachi-Yuta458 

この手順通りに作るのであればissueは以下のように切った方が良さそうですね！良いと思います！
* tagテーブルを作成する
* 必要となるタグデータをcreateする
* tagとquestionを関連づける(中間テーブル作成、リレーションの設定)
* 質問作成フォームにてタグを複数選択できるようにする
* コントローラー側でタグを登録できるようにする

安達さんに提示してもらったやり方がいわゆる正攻法だと思います！

**Comment by TomoyaIkarashi0023** [comment]
LGTM
